services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: leonan           
      POSTGRES_PASSWORD: leonanPASS    
      POSTGRES_DB: testeDB           
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  db_data:
  portainer_data:
