apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app-namespace
spec:
  replicas: 3  # 3 instâncias da aplicação
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app-container
        image: leonanmaycon/app:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "development"
        - name: DB_HOST
          value: "db-service"  # Nome do serviço do banco de dados
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app-namespace
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # Tipo de serviço para acessar a aplicação externamente (opcional)
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: app-namespace
spec:
  replicas: 1  # Apenas 1 instância do banco de dados
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: db-container
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: app-namespace
spec:
  selector:
    app: my-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: app-namespace
type: Opaque
data:
  POSTGRES_USER: cGFzc0RCVXNlcg==  # passDBUser em base64
  POSTGRES_PASSWORD: cGFzc0RCUGFzcw==  # passDBPass em base64
  POSTGRES_DB: cGFzc0RC  # passDB em base64
